name: "Deploy workflow for EKS cluster"

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
      aws_region:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup environment
        uses: ./.github/actions/setup-composite
        with:
          aws-region: ${{ inputs.aws_region }}
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.terraform_version }}
    
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: install eksctl
        run: |
          # for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7`
          ARCH=amd64
          PLATFORM=$(uname -s)_$ARCH
          curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
          # (Optional) Verify checksum
          curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
          tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
          sudo install -m 0755 /tmp/eksctl /usr/local/bin && rm /tmp/eksctl
      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name devopslab-eks \
            --region us-east-1

      - name: Configure aws load balancer controller
        run: |
          curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.13.3/docs/install/iam_policy.json
          aws iam create-policy \
            --policy-name AWSLoadBalancerControllerIAMPolicy \
            --policy-document file://iam_policy.json 2>/dev/null || echo "Policy already exists"

          if eksctl get iamserviceaccount --cluster devopslab-eks --namespace kube-system | grep -q aws-load-balancer-controller; then
            eksctl delete iamserviceaccount \
              --cluster=devopslab-eks \
              --namespace=kube-system \
              --name=aws-load-balancer-controller \
              --region us-east-1
          fi
          eksctl create iamserviceaccount \
            --cluster=devopslab-eks \
            --namespace=kube-system \
            --name=aws-load-balancer-controller \
            --attach-policy-arn=arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):policy/AWSLoadBalancerControllerIAMPolicy \
            --override-existing-serviceaccounts \
            --region us-east-1 \
            --approve

          if ! helm list -n kube-system | grep -q aws-load-balancer-controller; then
            helm repo add eks https://aws.github.io/eks-charts
            helm repo update
            helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
              -n kube-system \
              --set clusterName=devopslab-eks \
              --set serviceAccount.create=false \
              --set serviceAccount.name=aws-load-balancer-controller \
              --set region=us-east-1 \
              --set vpcId=$(aws eks describe-cluster --name devopslab-eks --region us-east-1 --query "cluster.resourcesVpcConfig.vpcId" --output text) \
              --set image.tag="v2.13.3"
          fi