name: "Deploy workflow for EKS cluster"

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      eks_cluster_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup environment
        uses: ./.github/actions/setup-composite
        with:
          aws-region: ${{ inputs.aws_region }}
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ inputs.eks_cluster_name }} \
            --region ${{ inputs.aws_region }}

      - name: Configure aws load balancer controller
        run: |
          curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.13.3/docs/install/iam_policy.json
          aws iam create-policy \
            --policy-name AWSLoadBalancerControllerIAMPolicy \
            --policy-document file://iam_policy.json 2>/dev/null || echo "Policy already exists"

          if eksctl get iamserviceaccount --cluster ${{ inputs.eks_cluster_name }} --namespace kube-system | grep -q aws-load-balancer-controller; then
            eksctl delete iamserviceaccount \
              --cluster=${{ inputs.eks_cluster_name }} \
              --namespace=kube-system \
              --name=aws-load-balancer-controller \
              --region ${{ inputs.aws_region }}
          else
            eksctl create iamserviceaccount \
              --cluster=${{ inputs.eks_cluster_name }} \
              --namespace=kube-system \
              --name=aws-load-balancer-controller \
              --attach-policy-arn=arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):policy/AWSLoadBalancerControllerIAMPolicy \
              --override-existing-serviceaccounts \
              --region ${{ inputs.aws_region }} \
              --approve
          fi

          helm repo add eks https://aws.github.io/eks-charts
          helm repo update
          wget https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml
          kubectl apply -f crds.yaml
          if helm list -n kube-system | grep -q aws-load-balancer-controller; then
            helm uninstall aws-load-balancer-controller -n kube-system
          else
            helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
              -n kube-system \
              --set clusterName=${{ inputs.eks_cluster_name }} \
              --set serviceAccount.create=false \
              --set serviceAccount.name=aws-load-balancer-controller \
              --set region=${{ inputs.aws_region }} \
              --set vpcId=$(aws eks describe-cluster --name ${{ inputs.eks_cluster_name }} --region ${{ inputs.aws_region }} --query "cluster.resourcesVpcConfig.vpcId" --output text) \
              --set image.tag="v2.13.3"
          fi