name: "Destroy workflow for EKS cluster"

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
      aws_region:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup environment
        uses: ./.github/actions/setup-composite
        with:
          aws-region: ${{ inputs.aws_region }}
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.terraform_version }}
    
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan for Destroy
        run: terraform plan -destroy

      - name: empty ecr images
        run: |
          repos=$(aws ecr describe-repositories \
            --region ${{ inputs.aws_region }} \
            --query "repositories[?starts_with(repositoryName, \`devopslab-\`)].repositoryName" \
            --output text 2>/dev/null || true)
          
          if [ -n "$repos" ]; then
            echo "$repos" | xargs -I {} -P 10 bash -c '
              repo_name="{}"
              images=$(aws ecr list-images --repository-name "$repo_name" --query "imageIds[*].imageDigest" --output text 2>/dev/null || true)
              if [ -n "$images" ]; then
                echo "$images" | xargs -I %% aws ecr batch-delete-image --repository-name "$repo_name" --image-ids imageDigest=%% || true
              fi
            '
          fi
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
