name: "Workflow to deploy an EKS cluster into AWS"

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'What action would you like to do?'
        required: true
        default: 'deploy'
        type: choice
        options:
          - 'deploy'
          - 'destroy'
  # push:
  #   paths-ignore:
  #     - '.github/**'
  #     - '.gitignore'
  #     - 'README.md'
  #   branches:
  #     - main

jobs:
  call-deploy-workflow:
    if: ${{ github.event.inputs.deploy == 'deploy' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      
  call-destroy-workflow:
    if: ${{ github.event.inputs.deploy == 'destroy' }}
    uses: ./.github/workflows/destroy.yml
    secrets: inherit
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}